spring:
  application:
    name: sboot-tasks-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_DATASOURCE_USERNAME}
    password: ${MYSQL_DATASOURCE_PASSWORD}

server:
  error:
    include-stacktrace: never
    include-message: always

#https://cursos.alura.com.br/course/spring-boot-aplique-boas-praticas-proteja-api-rest/task/117151