spring:
  application:
    name: login-auth-api

  datasource:
    url: jdbc:mysql://192.168.0.18:3306/cmdevdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cmdev_user
    password: access01@CMDEV

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
api:
  security:
    token:
      secret: my-secret-key-from-video