spring:
  application:
    name: spring-oauth
    description: Demo project for Spring Boot with OAuth 2.0
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enable: false
management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmdevdb?useTimezone=true?serverTimezone=UTC?useUnicode=yes?characterEncoding=UTF-8?useSSL=false
    username: cmdev_user
    password: access01@CMdev
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: local

  devtools:
    add-properties: true

logging:
  level:
    web: DEBUG


springdoc:
  packages-to-scan: br.com.cmdev.springoauth.controllers
  api-docs:
    enabled: true
  swagger-ui:
    path: documentation
    enabled: true
    operationsSorter: method
    tryItOutEnabled: true
    filter: true
    tagsSorter: alpha