#server:
#  error:
#    whitelabel:
#      enabled: false

#spring-doc:
#  enable-native-support: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
